export default {
  "forcePairing": false,
  "pairingType": "PROMPT",
  "manifest": {
    "manifestVersion": 1,
    "appVersion": "1.0",
    "deviceName": "LG Mobile",
    "allowFullPagePopup": true,
    "allowFirstuseConnection": true,
    "signed": {
      "created": "20150330",
      "appId": "com.lge.test",
      "vendorId": "com.lge",
      "localizedAppNames": {
        "": "LG Mobile",
        "ko-KR": "LG Mobile",
        "zxx-XX": "LG Mobile"
      },
      "localizedVendorNames": {
        "": "LG Electronics"
      },
      "permissions": [
        "TEST_SECURE",
        "CONTROL_INPUT_TEXT",
        "CONTROL_MOUSE_AND_KEYBOARD",
        "READ_INSTALLED_APPS",
        "READ_LGE_SDX",
        "READ_NOTIFICATIONS",
        "SEARCH",
        "WRITE_SETTINGS",
        "WRITE_NOTIFICATION_ALERT",
        "CONTROL_POWER",
        "READ_CURRENT_CHANNEL",
        "READ_RUNNING_APPS",
        "READ_UPDATE_INFO",
        "UPDATE_FROM_REMOTE_APP",
        "READ_LGE_TV_INPUT_EVENTS",
        "READ_TV_CURRENT_TIME",
        "CONTROL_BLUETOOTH",
        "CHECK_BLUETOOTH_DEVICE",
        "CONTROL_VOICE",
        "ACCESS_STORAGE",
        "SECURE_ACCESS_PUSH",
        "SECURE_APP_TO_APP",
        "SECURE_CONTROL_CHANNEL_BLOCK",
        "SECURE_CONTROL_CHANNEL_GROUP",
        "SECURE_CONTROL_DISPLAY",
        "SECURE_CONTROL_FAVORITE_GROUP",
        "SECURE_CONTROL_POWER",
        "SECURE_CONTROL_TV_SCREEN",
        "SECURE_DELETE_SELECT_CHANNEL",
        "SECURE_LAUNCH",
        "SECURE_READ_INPUT_DEVICE_LIST",
        "SECURE_READ_INSTALLED_APPS",
        "SECURE_READ_NETWORK_STATE",
        "SECURE_READ_RUNNING_APPS",
        "SECURE_READ_STORAGE_DEVICE_LIST",
        "SECURE_READ_TV_CHANNEL_LIST",
        "SECURE_READ_TV_PROGRAM_INFO",
        "SECURE_RELEASE_CHANNEL_SKIP",
        "SECURE_SCAN_TV_CHANNELS",
        "SECURE_SET_CHANNEL_SKIP",
        "SECURE_WRITE_RECORDING_SCHEDULE",
        "CONTROL_DAFC_CALIBRATION"
      ],
      "serial": "49d0233e26a3fc4d3113ddbc22a8686a"
    },
    "permissions": [
      "LAUNCH",
      "LAUNCH_WEBAPP",
      "APP_TO_APP",
      "CONTROL_AUDIO",
      "CONTROL_INPUT_MEDIA_PLAYBACK",
      "UPDATE_FROM_REMOTE_APP",
      "CONTROL_POWER",
      "READ_INSTALLED_APPS",
      "CONTROL_DISPLAY",
      "CONTROL_INPUT_JOYSTICK",
      "CONTROL_INPUT_MEDIA_RECORDING",
      "CONTROL_INPUT_TV",
      "READ_INPUT_DEVICE_LIST",
      "READ_NETWORK_STATE",
      "READ_TV_CHANNEL_LIST",
      "WRITE_NOTIFICATION_TOAST",
      "CONTROL_BLUETOOTH",
      "CHECK_BLUETOOTH_DEVICE",
      "CONTROL_USER_INFO",
      "CONTROL_TIMER_INFO",
      "READ_SETTINGS",
      "CONTROL_TV_SCREEN",
      "CONTROL_INPUT_TEXT",
      "CONTROL_MOUSE_AND_KEYBOARD",
      "READ_CURRENT_CHANNEL",
      "READ_RUNNING_APPS",
      "READ_TV_PROGRAM_INFO",
      "READ_STORAGE_DEVICE_LIST"
    ],
    "signatures": [
      {
        "signatureVersion": 1,
        "signature": "eyJhbGdvcml0aG0iOiJSU0EtU0hBMjU2Iiwia2V5SWQiOiJ0ZXN0LXNpZ25pbmctY2VydCIsInNpZ25hdHVyZVZlcnNpb24iOjF9.HWKCin7TZ40rKXxZeqq1O++3mTrs9OwE06f5/fNans0/mK8uPmIl4H/ADmal/ymoY8WjIMucwiKCqaPiJoU5wnRu+8rdC/iA+S76ap+KYfRjg7uD55jCvAfYieal0NopEJmVTts5B8bXluZUlLFq53N7VfNGAt5VhjcgwUV6fmOIHIh7md/Y55I5lZTdMIGkuXC7AzCGc0swNWupbblMwAn5aG4ljSXh4paUDFkRoq/g0cHN/jNHZrbHW2e0b5yYAtA8iQMdjqxlD9q1OqYxiiO4zWefX0004CFNtgPv/fzdE6Eip53W6MCyX6l2+Yq9U9huh9qawI1QuSKx5cI14A=="
      }
    ]
  }
};
